### ISSUE TITLE
Flag icons broken on Windows.

### ISSUE THREAD

**Issue by TannerMarshall551** [Medusa-ML/TranslateTribune#30]
On the page displaying the different articles in your selected language the flag icons come up as the countries 2 letter code instead if you are on Windows computer.

**Comment by predbrad** [comment]
Opera and Chrome on Windows seem to be broken. Firefox is not... It's a browser specific rendering thing.

See tho following notes:

- https://www.reddit.com/r/chrome/comments/7gc9kp/help_flag_emojis_dont_show_up_in_chrome/
- https://github.com/nolanlawson/emoji-picker-element/issues/269
- https://stackoverflow.com/questions/54519758/flag-emojis-not-rendering

I think this is a "won't fix" for now. but I'll leave it open.
