### ISSUE TITLE
Absence of Right to Left(RTL) UI & UX feature for right oriented languages — Arabic, Farsi, Hebrew

### ISSUE THREAD

**Issue by ruslanpitula** [Medusa-ML/TranslateTribune#38]
It was spotted that application is featuring RTL languages such as Arabic, Farsi and Hebrew but the UI is still LTR oriented.
<img width="1792" alt="image" src="https://github.com/Medusa-ML/TranslateTribune/assets/91199564/24cc79c1-7a6e-4e45-ac68-41451803dc9c">
<img width="1792" alt="image" src="https://github.com/Medusa-ML/TranslateTribune/assets/91199564/47ecb58f-8a2f-486e-ab65-a8b4853b531f">
<img width="1792" alt="image" src="https://github.com/Medusa-ML/TranslateTribune/assets/91199564/36c66ab5-08fb-40e6-8aa4-5cc91fcf25f8">

**Comment by ruslanpitula** [comment]
Pull request: https://github.com/Medusa-ML/TranslateTribune/pull/39

**Comment by predbrad** [comment]
Fixed!
