### ISSUE TITLE
Menu isn't fully visible on new mobile page

### ISSUE THREAD

**Issue by predbrad** [Medusa-ML/TranslateTribune#44]
![Screenshot from 2024-05-08 17-20-07](https://github.com/Medusa-ML/TranslateTribune/assets/16511019/e647a52f-8e58-4bdb-a558-c4c98eabadd0)

See attached screenshot, menu doesn't scale properly on mobile.

**Comment by oleksandrfomin5995** [comment]
@predbrad 
The navbar is scrollable as per the design 
![image](https://github.com/Medusa-ML/TranslateTribune/assets/111069023/18f4ff91-5d12-49ba-bb64-84bb796a4454)

We can add an arrow for auto-scroll to the rightmost and leftmost positions to make it more intuitive. Or rework the design for mobile screens

**Comment by predbrad** [comment]
This is fine then.

**Comment by predbrad** [comment]
I changed my mind. I want us to be proud of the design. I think we should make it better. @oleksandrfomin5995 and fyi @ruslanpitula

I'm sorry I didn't see this in the original design but I think we need our mobile webpage to be pretty and fully functional, otherwise we are advertising not the best product.

**Comment by MarsDandelion** [comment]
Hi @predbrad if you want the arrow to show the direction for other entity, we can discuss these variants.
<img width="944" alt="Снимок экрана 2024-05-09 в 12 27 34" src="https://github.com/Medusa-ML/TranslateTribune/assets/39186721/8b11799a-b5ad-43d0-b685-59cf87f82672">

**Comment by predbrad** [comment]
@MarsDandelion let's add the black arrow with the circle. That looks much better. Thank you!

**Comment by MarsDandelion** [comment]
Thank you @predbrad, done!

**Comment by MarsDandelion** [comment]
@predbrad sorry for this, but could you please clarify which exactly arrow? 1 variant or 2 variant? 

Because circle is only black, and arrow in the circle is white)

**Comment by predbrad** [comment]
good
