### ISSUE TITLE
Add link to Public Flutter Repository

### ISSUE THREAD

**Issue by predbrad** [Medusa-ML/TranslateTribune#48]
We should share the flutter app code, it can live in this repo or in a separate open repo if we like @ruslanpitula

**Comment by predbrad** [comment]
We should also add app store and play store links to the repo

**Comment by ruslanpitula** [comment]
@predbrad we'll prepare a separate GitHub open repo. I don't like the idea of overloading this repo

**Comment by predbrad** [comment]
@ruslanpitula agreed
