### ISSUE TITLE
Website update broke flags on App

### ISSUE THREAD

**Issue by predbrad** [Medusa-ML/TranslateTribune#49]
See screenshot. We are using PNGs now and not emojis on the website and now the app has no flags. 
![Screenshot_20240508-195452](https://github.com/Medusa-ML/TranslateTribune/assets/16511019/394bac98-1244-47a6-a1c3-506b795ff146)

**Comment by oleksandrfomin5995** [comment]
Couldn't reproduce this one

**Comment by predbrad** [comment]
@oleksandrfomin5995 open the Android app, and you should see flags are missing, when you saw maybe the old website was still up.
