### ISSUE TITLE
Make sure App points to correct patreon, if at all.

### ISSUE THREAD

**Issue by predbrad** [Medusa-ML/TranslateTribune#69]
Should the inoxoft app be pointing to the patreon? or to Inoxoft? 

if it points to patreon, make sure it points to https://www.patreon.com/medusaintel

**Comment by ruslanpitula** [comment]
@predbrad We removed it on purpose. As this rule was never published anywhere by any of "Stores", but it is not a good practice to include Patreon link at the release, as it attracts more attention of reviewer. We can add this few month later after releases

**Comment by predbrad** [comment]
@ruslanpitula let's keep it off. All good.
